title: Jeffrey K Ledbetter   # your name (or website title) here
logo: "/images/passport_afghn.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Personal description 
  <br>Current Masters student in Geographical Information Technologies at the University of Oklahoma.
  Undergraduate studies included a BS in Geography and Environmental Sustainability
  with a focus in Geographical Information Systems and a BA in Administration of Justice
  with a Minor in Environmental Science from Southern Illinois University at Carbondale.<br>
  Software Knowledge 
  <br>ESRI Arcdesktop, ArcPro, ArcGIS Online, GeoApps, Python, RStudio, GitHub, PostGIS,
  PostSQL, OpenRefine, Google Earth Engine, Microsoft Office.
  Email: jkledbetter6070@gmail.com<br>
  <a href="https://www.linkedin.com/in/jeffrey-ledbetter-492740201/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

